board: MKS TinyBee V1.0 XXYYZ
name: FRCNC

# Power with 12V
# connect fan to +12/24- connecton (always on)
#
# Board desig.   |  I/O  | I/O pin | Description
# --------------------------------------------------------------
# HE0            |  in   |  IO145  | Used to activate solenoid for mist
# HE1            |  in   |  IO146  | Used for relay to run Vacuum
# H-BED          |  in   |  IO144  | Not used 
# X Limit        |  in   |  IO33   | X limit switch 1
# Y Limit        |  in   |  IO32   | X limit switch 2
# Z limit        |  in   |  IO22   | Y limit switch
# MT_DET         |  in   |  IO16   | Z limit (conductive touch sensor) IO35 is FRAUGHT WITH PERIL, use 39 - no use 16 because 39 does not support low:pu
# TH1            |  in   |  IO36   | Feed Hold pin
# TH2            |  in   |  IO34   | Cycle start pin 
# TB             |  in   |   NC    | Reset pin (not connected)
# SPINDLE PWM    | out   |  IO17   |
# SPINDLE ENA    | out   |  

# 3DTOUCH (out)  |  out  | SPINDLE?
# FAN1           |  12V  |
# FAN2           |  12V  |

# H-E0  (i2so17) | out-12V | - mist


kinematics:
  Cartesian:

i2so:
  bck_pin: gpio.25
  data_pin: gpio.27
  ws_pin: gpio.26

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  # uses TH2 IO34 active low - MAKE SURE jumper J2 is set to SDDET!!!
  # NOT USED card_detect_pin: gpio.34:low

stepping:
  engine: I2S_STATIC
  idle_ms: 255
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 2

axes:
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 120.000
    max_travel_mm: 1350.000
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: -60.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1500.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    # use X driver for 1st X axis motor
    motor0:
      limit_neg_pin: gpio.33:low:pu
      hard_limits: true
      pulloff_mm: 6.000
      standard_stepper:
        step_pin: I2SO.1
        direction_pin: I2SO.2
        disable_pin: I2SO.0

    # use Y driver for 2nd X axis motor
    motor1:
      limit_neg_pin: gpio.32:low:pu
      hard_limits: true
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.4
        direction_pin: I2SO.5
        disable_pin: I2SO.3

  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 120.000
    max_travel_mm: 760.000
    soft_limits: true
    homing:
      cycle: 3
      positive_direction: false
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    # use Z driver for Y axis motor
    motor0:
      limit_neg_pin: gpio.22:low:pu
      hard_limits: true
      pulloff_mm: 2.000
      standard_stepper:
        step_pin: I2SO.7
        direction_pin: I2SO.8
        disable_pin: I2SO.6

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 8000.000
    acceleration_mm_per_sec2: 60.000
    max_travel_mm: 200.000
    soft_limits: false
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0.000
      feed_mm_per_min: 300.000
      seek_mm_per_min: 1000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    # use E0 driver for Z axis motor
    motor0:
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3.000
      standard_stepper:
        step_pin: I2SO.10
        direction_pin: I2SO.11
        disable_pin: I2SO.9

probe:
  pin: gpio.36:low
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false

control:
  safety_door_pin: NO_PIN
  # on MT_DET connector
  reset_pin: gpio.34:low
  # on TH1 connector
  feed_hold_pin: NO_PIN
  # on TB connector
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN

coolant:
  # Heated Bed Terminal Block
  flood_pin: i2so.18
  # HE0 Terminal Block
  mist_pin: i2so.17
  delay_ms: 0

# spindle PWM signal
PWM:
  enable_pin: i2so.16
  pwm_hz: 2500
  # on EXP1 IO15 connector.
  # note IO15 will give some short pulses on boot, which may activate spindle
  # use IO17 on EXP1 to avoid
  output_pin: gpio.17:high
  s0_with_disable: true
  tool_num: 0
  spinup_ms: 4000
  spindown_ms: 4000
  speed_map: 0=0.000% 12000=100.000%

Laser:
  pwm_hz: 5000
  # on 3D Touch connector (has pdwn + PWM)
  output_pin: gpio.2:high:pd
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 1000=100.000%

start:
  must_home: false